services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: link_backend
    restart: unless-stopped
    env_file: ./apps/backend/.env
    ports:
      - '5000:5000'
    volumes:
      - uploads:/app/apps/backend/uploads
    networks:
      - link_network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: link_frontend
    restart: unless-stopped
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - link_network

volumes:
  uploads:

networks:
  link_network:
    driver: bridge
